using UnityEngine;
using System.Collections;

public class DialogEndWithGrab: MonoBehaviour {
	
	void Start(){
		
		transform.GetComponent<DUGView>().visible = false;
		
		string triggerName = transform.GetComponent<DialogueController>().activeDialogue;
		
		
		
		if(triggerName == "")
			return;

		GameObject.Find(triggerName).GetComponent<TriggerHandler>().moveCameraToPlayer();
		GameObject.Find(triggerName).GetComponent<TriggerHandler>().enableCameraAndMotor();
		GameObject.Find(triggerName).GetComponent<TriggerHandler>().mouseClick = false;
		//set lock to false so others can interact with this object
		GameObject.Find(triggerName).GetComponent<TriggerHandler>().photonView.RPC("setInteractLock",PhotonTargets.AllBuffered, false);
		
		//delete the useless script generated by dunilog
		GameObject targetObj = findChildWithTag(GameObject.Find(triggerName).transform);

		if(targetObj != null)
		{
		moveToPlayerPosition(targetObj);
		disableRender(targetObj);
		disableCollider (targetObj);
		enableInventory(targetObj);
		}


		GameObject.Destroy(this.gameObject.transform.GetComponent<DialogEnd>());
		//this.transform.parent.GetComponent<TriggerHandler>().moveCameraToPlayer();
		//this.transform.parent.GetComponent<TriggerHandler>().enableCameraAndMotor();
	}
	void moveToPlayerPosition(GameObject obj){
		obj.transform.position = this.transform.position;
		obj.transform.parent = this.transform;

	}

	GameObject findChildWithTag( Transform parent){
		foreach (Transform child in parent){
			if(child.gameObject.tag == "grab"){
				print (child.gameObject.name);
				return child.gameObject;
			}
		}

		return null;

	}

	void disableCollider(GameObject obj){
		Collider[] colliders = obj.GetComponentsInChildren<Collider>();
		
		foreach ( Collider c in colliders)
		{
			if(c.enabled == true)
				c.enabled = false;
		}

	}
	void disableRender(GameObject obj)
	{
		Renderer[] renderers = obj.GetComponentsInChildren<Renderer>();

		foreach ( Renderer r in renderers)
		{
			if(r.enabled == true)
				r.enabled = false;
		}
	}

	void enableInventory(GameObject obj){

		GameObject.Find ("Inventory").GetComponent<inventory>().updateInventoryObject(obj);

	}
}
